version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2

jobs:
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - snyk/scan:
          if [ -f package.json ] || [ -f requirements.txt ] || [ -f pom.xml ] then
            command:  monitor
          else
            echo "No manifest file found. Skipping Snyk scan."
          fi
          monitor-on-build: false

workflows:
  build-test-snyk:
    jobs:
      - snyk-scan
